sudo: false

language: python

matrix:
  include:
    - python: '3.6'
      env: TESTENV=lint
    - python: '3.6'
      env:
        - TESTENV=py36
        - ERRBOT_VERSION=5.2.0
    - python: '3.6'
      env:
        - TESTENV=py36
        - ERRBOT_VERSION=6.0.0a0
    - python: '3.7-dev'
      env:
        - TESTENV=py36
        - ERRBOT_VERSION=5.2.0

before_script:
  - pip install 'flake8>=3.6.0,<3.7.0' pydocstyle pytest
  - if [ "$TESTENV" != "lint" ]; then pip install "errbot==$ERRBOT_VERSION"; fi

script:
  - if [ "$TESTENV" = "lint" ];  then flake8; fi
  - if [ "$TESTENV" = "lint" ];  then pydocstyle; fi
  - if [ "$TESTENV" != "lint" ]; then pytest tests.py; fi
