sudo: false

language: python

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7-dev'
      env: TOXENV=py37

before_script:
  - pip install 'flake8>=3.6.0,<3.7.0' pydocstyle

script:
  - flake8
  - pydocstyle

